"""Add Follow table, User.followed and User.followers

Revision ID: 67acd850e3d8
Revises: d154b86a83e8
Create Date: 2017-09-09 07:54:40.031175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67acd850e3d8'
down_revision = 'd154b86a83e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
