"""Add confirmed column to db. Add generate_confirmation_token and confirm methods

Revision ID: fddf0d56a11f
Revises: 03f802e5128d
Create Date: 2017-08-25 06:57:28.198090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddf0d56a11f'
down_revision = '03f802e5128d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
